Traceback (most recent call last):
  File "/home/earpte/anaconda3/envs/jupyterbook/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/earpte/anaconda3/envs/jupyterbook/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/earpte/anaconda3/envs/jupyterbook/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/earpte/anaconda3/envs/jupyterbook/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/earpte/anaconda3/envs/jupyterbook/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/earpte/anaconda3/envs/jupyterbook/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/earpte/anaconda3/envs/jupyterbook/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/earpte/anaconda3/envs/jupyterbook/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
problem1(1000)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mUnboundLocalError[0m                         Traceback (most recent call last)
Cell [0;32mIn [4], line 1[0m
[0;32m----> 1[0m [43mproblem1[49m[43m([49m[38;5;241;43m1000[39;49m[43m)[49m

Cell [0;32mIn [3], line 5[0m, in [0;36mproblem1[0;34m(N)[0m
[1;32m      3[0m [38;5;28;01mfor[39;00m i [38;5;129;01min[39;00m [38;5;28mrange[39m(N):
[1;32m      4[0m     [38;5;28;01mif[39;00m i [38;5;241m%[39m [38;5;241m3[39m [38;5;241m==[39m [38;5;241m0[39m [38;5;129;01mor[39;00m i [38;5;241m%[39m [38;5;241m5[39m [38;5;241m==[39m [38;5;241m0[39m:
[0;32m----> 5[0m         j [38;5;241m+[39m[38;5;241m=[39m i
[1;32m      6[0m [38;5;28;01mreturn[39;00m solution

[0;31mUnboundLocalError[0m: local variable 'j' referenced before assignment
UnboundLocalError: local variable 'j' referenced before assignment

